name: impaza
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.prod
    container_name: impaza_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    env_file:
      - .env.prod
    environment:
      TZ: Africa/Harare
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: "https://impazamon.powertel.co.zw"
      DB_CONNECTION: mysql
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_DATABASE: impaza
      DB_USERNAME: impaza
      DB_PASSWORD: Power@Dev25
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      REDIS_HOST: redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    networks:
      - impaza

  scheduler:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.prod
    container_name: impaza_scheduler
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    env_file:
      - .env.prod
    environment:
      TZ: Africa/Harare
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: "https://impazamon.powertel.co.zw"
      DB_CONNECTION: mysql
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_DATABASE: impaza
      DB_USERNAME: impaza
      DB_PASSWORD: Power@Dev25
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      REDIS_HOST: redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    command: ["php", "artisan", "schedule:work"]
    networks:
      - impaza

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: impaza_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
      - /var/www/html/impaza/storage:/var/www/html/storage:ro
      # Directly mount public storage into Nginx web root to ensure /storage/* is served
      - /var/www/html/impaza/storage/app/public:/var/www/html/public/storage:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      TZ: Africa/Harare
    depends_on:
      - app
    networks:
      - impaza

  certbot:
    image: certbot/certbot
    container_name: impaza_certbot
    restart: "no"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


  redis:
    image: redis:alpine
    container_name: impaza_redis
    restart: unless-stopped
    environment:
      TZ: Africa/Harare
    networks:
      - impaza

networks:
  impaza:
    driver: bridge
