services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      TZ: Africa/Harare
    depends_on:
      - mysql
      - redis
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      TZ: Africa/Harare
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: impaza
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      TZ: Africa/Harare
    command: ["--default-time-zone=+02:00"]
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"  # mapped to avoid host 3306 conflicts
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - "6380:6379"  # mapped to host
    environment:
      TZ: Africa/Harare
    networks:
      - laravel

  # -----------------------------
  # phpMyAdmin (Web GUI for MySQL)
  # -----------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"  # access via http://localhost:8081
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
      TZ: Africa/Harare
    depends_on:
      - mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
