version = 5.4.0
archive_dir = /etc/letsencrypt/archive/impazamon.powertel.co.zw
cert = /etc/letsencrypt/live/impazamon.powertel.co.zw/cert.pem
privkey = /etc/letsencrypt/live/impazamon.powertel.co.zw/privkey.pem
chain = /etc/letsencrypt/live/impazamon.powertel.co.zw/chain.pem
fullchain = /etc/letsencrypt/live/impazamon.powertel.co.zw/fullchain.pem
[renewalparams]
account = d84b475339ebab86426aaa2615c71135
rsa_key_size = 4096
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
[acme_renewal_info]
ari_retry_after = 2026-04-01T19:35:06
